# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=find_table_caption_a1ab437946
ROOST_METHOD_SIG_HASH=find_table_caption_09a7b31375


```
Scenario 1: Test when the HTML content contains a table with the desired caption.
Details:
  TestName: test_find_table_caption_with_valid_input
  Description: This test verifies the function's ability to correctly identify a table with the specified caption in the HTML content.
Execution:
   Arrange: Load mockup HTML content that contains a table with the caption "Anscombe's quartet" into BeautifulSoup object.
   Act: Invoke the find_table_caption() function with the BeautifulSoup object and caption "Anscombe's quartet".
   Assert: Check that the returned tag is the table with the specified caption.
Validation:
  This test validates that the function correctly searches and identifies the table with the specified caption from the HTML content. This is vital as this key functionality of the function.

Scenario 2: Test when the desired caption is not available in the HTML content.
Details:
  TestName: test_find_table_caption_with_invalid_caption
  Description: This test verifies how the function behaves when the table with the desired caption is not present in the HTML content.
Execution:
   Arrange: Load mockup HTML content that does not contain a table with the caption "Anscombe's quartet" into BeautifulSoup object.
   Act: Invoke the find_table_caption() function with the BeautifulSoup object and caption "Anscombe's quartet".
   Assert: Check that a RuntimeError is raised with an appropriate message.
Validation:
  This test is vital as it checks that the function correctly notifies the user (through a RuntimeError) when the desired caption is not found. This is foundational to safeguard against false-positives.

Scenario 3: Test the function's handling of HTML content without any tables.
Details:
  TestName: test_find_table_caption_without_tables
  Description: This test investigates the function's reaction to HTML content without any tables.
Execution:
   Arrange: Load mockup HTML content with no tables into BeautifulSoup object.
   Act: Invoke the find_table_caption() function with the BeautifulSoup object and any caption.
   Assert: Check that a RuntimeError is raised with an appropriate message.
Validation:
  This test is vital to confirm the function's aptitude in notifying the user when the HTML content has no tables at all, ensuring accurate and user-friendly output.

Scenario 4: Test the function's case-insensitivity when comparing captions.
Details:
  TestName: test_find_table_caption_case_insensitivity
  Description: This test examines the function's ability to find the table irrespective of the casing of the caption text.
Execution:
   Arrange: Load mockup HTML content that contains a table with the caption "Anscombe's quartet" into BeautifulSoup object.
   Act: Invoke the find_table_caption() function with the BeautifulSoup object and caption "aNsCoMbE's QuArTeT".
   Assert: Check that the returned tag is the table with the specified caption.
Validation:
  This test confirms that the function is case-insensitive, which is required to increase flexibility and usability.
"""

# ********RoostGPT********
import pytest
from bs4 import BeautifulSoup, Tag
from urllib.request import urlopen
from html_extract import find_table_caption

class Test_HtmlExtractFindTableCaption():

    @pytest.mark.smoke
    def test_find_table_caption_with_valid_input(self):
        mockup_html_content = '''<html><head><title>Test Page</title></head>
                                <body><table><caption>Anscombe's quartet</caption></table></body></html>'''
        soup = BeautifulSoup(mockup_html_content, 'html.parser')
        result = find_table_caption(soup, "Anscombe's quartet")
        assert isinstance(result, Tag), "Return type is not Tag"
        assert result.caption.text.strip() == "Anscombe's quartet", "Caption not found in HTML content"

    @pytest.mark.regression
    def test_find_table_caption_with_invalid_caption(self):
        mockup_html_content = '''<html><head><title>Test Page</title></head>
                                <body><table><caption>Other Table</caption></table></body></html>'''
        soup = BeautifulSoup(mockup_html_content, 'html.parser')
        with pytest.raises(RuntimeError) as e:
            find_table_caption(soup, "Anscombe's quartet")
        assert "with <caption>Anscombe's quartet</caption> not found" in str(e.value), "Unexpected error message received"

    @pytest.mark.regression
    def test_find_table_caption_without_tables(self):
        mockup_html_content = '''<html><head><title>Test Page</title></head><body></body></html>'''
        soup = BeautifulSoup(mockup_html_content, 'html.parser')
        with pytest.raises(RuntimeError) as e:
            find_table_caption(soup, "Anscombe's quartet")
        assert "with <caption>Anscombe's quartet</caption> not found" in str(e.value), "Unexpected error message received"

    @pytest.mark.smoke
    def test_find_table_caption_case_insensitivity(self):
        mockup_html_content = '''<html><head><title>Test Page</title></head>
                                <body><table><caption>Anscombe's quartet</caption></table></body></html>'''
        soup = BeautifulSoup(mockup_html_content, 'html.parser')
        result = find_table_caption(soup, "aNsCoMbE's QuArTeT")
        assert isinstance(result, Tag), "Return type is not Tag"
        assert result.caption.text.strip().lower() == "anscombe's quartet", "Caption not found in HTML content"
