# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=table_row_data_iter_93090a5698
ROOST_METHOD_SIG_HASH=table_row_data_iter_2cb334357f


```
Scenario 1: Referencing an HTML table with data
Details:
  TestName: test_iter_with_data_table
  Description: This test ensures that the function can correctly iterate through an HTML table with data and generate a correct ordered list for each row.
Execution:
  Arrange: Prepare a BeautifulSoup HTML object simulating a table with several rows and cells with known data.
  Act: Run the table_row_data_iter function with the HTML table.
  Assert: The yielded lists from the Iterator should accurately represent the text within each cell, stripped of whitespace and in their original order.
Validation:
  This test is fundamental because it's the primary use case of the function. It confirms the reliable conversion of HTML tables into iterable Python data.

Scenario 2: Empty table handling
Details:
  TestName: test_iter_with_empty_table
  Description: Test the function with an empty table, with no tbody or tr elements.
Execution:
  Arrange: Prepare a BeautifulSoup HTML object simulating an empty table.
  Act: Run the table_row_data_iter function with the empty table.
  Assert: The Iterator should not yield any lists as there is no data in the table.
Validation:
  Checking the function's response to edge cases such as an empty table ensures that it exhibits graceful error handling and robustness in face of undesired/invalid inputs.

Scenario 3: Table only containing header (thead), not body (tbody)
Details:
  TestName: test_iter_with_header_only_table
  Description: Test the function with a table that only includes header cells (th), but no body cells (td).
Execution:
  Arrange: Prepare a BeautifulSoup HTML object simulating a table with thead elements but no tbody.
  Act: Run the function with the header-only table.
  Assert: The Iterator should not yield any lists as there are no td elements in the table.
Validation:
  This test case ensures that the function only considers tbody and td elements, ignoring th elements, aligning with HTML table semantics.

Scenario 4: Nested table handling 
Details:
  TestName: test_iter_with_nested_table
  Description: Test the function with a table that contains nested tables within its td cells.
Execution:
  Arrange: Prepare a BeautifulSoup HTML object simulating a table with several rows and cells, some of which have nested table data.
  Act: Run the function with the nested table.
  Assert: The nested table's data should be included in the respective list as per the cell it lies in.
Validation:
  Testing with nested tables ensures that the function can handle complex HTML tables, demonstrating its versatility and resilience to unconventional data structures.

Scenario 5: Table with merged cells
Details:
  TestName: test_iter_with_merged_cells_table
  Description: Test the function with a table that has merged cells (colspan attribute).
Execution:
  Arrange: Prepare a BeautifulSoup HTML object simulating a table with merged cells.
  Act: Run the function with the table.
  Assert: Should correctly yield the data, taking into account the colspan attribute during the conversion from HTML table to a list of lists.
Validation:
  This scenario validates the function's ability to handle more complex table structures that include rowspan or colspan, confirming its adaptability to various HTML table designs.
```
"""

# ********RoostGPT********
# Dependencies
import pytest
from bs4 import BeautifulSoup
from html_extract import table_row_data_iter

class Test_HtmlExtractTableRowDataIter:
    
    @pytest.mark.smoke
    def test_iter_with_data_table(self):
        html = '''<table>
                    <tbody>
                        <tr><td>cell_1_1</td><td>cell_1_2</td></tr>
                        <tr><td>cell_2_1</td><td>cell_2_2</td></tr>
                    </tbody>
                  </table>'''
        soup = BeautifulSoup(html, 'html.parser')
        assert list(table_row_data_iter(soup.table)) == [['cell_1_1', 'cell_1_2'], ['cell_2_1', 'cell_2_2']]

    @pytest.mark.regression
    def test_iter_with_empty_table(self):
        html = '<table></table>'
        soup = BeautifulSoup(html, 'html.parser')
        assert list(table_row_data_iter(soup.table)) == []
      
    @pytest.mark.regression
    def test_iter_with_header_only_table(self):
        html = '''<table>
                    <thead>
                        <tr><th>header_1</th><th>header_2</th></tr>
                        <tr><th>header_3</th><th>header_4</th></tr>
                    </thead>
                  </table>'''
        soup = BeautifulSoup(html, 'html.parser')
        assert list(table_row_data_iter(soup.table)) == []
 
    @pytest.mark.regression
    def test_iter_with_nested_table(self):
        html = '''<table>
                    <tbody>
                        <tr><td>cell_1</td><td>cell_2
                            <table>
                                <tbody>
                                    <tr><td>nested_1</td><td>nested_2</td></tr>
                                </tbody>
                            </table>
                        </td></tr>
                    </tbody>
                  </table>'''
        soup = BeautifulSoup(html, 'html.parser')
        assert list(table_row_data_iter(soup.table)) == [['cell_1', 'cell_2'], ['nested_1', 'nested_2']]
        
    @pytest.mark.regression
    def test_iter_with_merged_cells_table(self):
        html = '''<table>
                    <tbody>
                        <tr><td rowspan="2">merged</td><td>cell_1</td></tr>
                        <tr><td>cell_2</td></tr>
                    </tbody>
                  </table>'''
        soup = BeautifulSoup(html, 'html.parser')
        assert list(table_row_data_iter(soup.table)) == [['merged', 'cell_1'], ['merged', 'cell_2']]
