# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=table_row_data_iter_93090a5698
ROOST_METHOD_SIG_HASH=table_row_data_iter_2cb334357f


```
Scenario 1: Valid table data
Details:
  TestName: test_table_row_data_iter_valid_table
  Description: This test verifies that the table_row_data_iter function returns the correct text in each table data cell.
Execution:
  Arrange: Prepare a BeautifulSoup object of a HTML with a valid table and tbody.
  Act: Invoke the function table_row_data_iter with the BeautifulSoup object as parameter.
  Assert: Check if the output matches the text present in table data cells.
Validation: 
  This is important to ensure the function works correctly with valid inputs and returns the correct result.

Scenario 2: Table without tbody
Details:
  TestName: test_table_row_data_iter_no_tbody
  Description: This test verifies whether the function can handle tables without a tbody.
Execution:
  Arrange: Prepare a BeautifulSoup object with a HTML that includes a table without tbody.
  Act: Invoke the function with this BeautifulSoup object.
  Assert: Because there is no tbody tag, the function should skip this table and return an empty iterator.
Validation:
  Real-world HTML may have tables without tbody tags, so the function needs to handle this case gracefully.

Scenario 3: No table data
Details:
  TestName: test_table_row_data_iter_no_data
  Description: This test verifies that the function returns an iterator yielding an empty list when there's no data in table.
Execution:
  Arrange: Prepare a BeautifulSoup object with a HTML containing table with tbody but no tr and td tags.
  Act: Invoke the function with this BeautifulSoup object.
  Assert: The function should return an iterator yielding an empty list.
Validation:
  It's critical for this function to handle tables with tbody but no data, returning an empty list instead of a Null or Error.

Scenario 4: Nested tables
Details:
  TestName: test_table_row_data_iter_nested_tables
  Description: This test verifies the function's capability to handle nested tables.
Execution:
  Arrange: Prepare an HTML with a table nested inside another table's cell and convert it to BeautifulSoup object.
  Act: Invoke the function with BeautifulSoup object.
  Assert: Check if the function returns the text from the outer table without recursing into the nested table.
Validation:
  Nested tables are real-world scenarios and the function should be able to exclude them from its results.
```

"""

# ********RoostGPT********
import pytest
from bs4 import BeautifulSoup, Tag
from collections.abc import Iterator
from urllib.request import urlopen
from html_extract import table_row_data_iter


class Test_HtmlExtractTableRowDataIter:

    def test_table_row_data_iter_valid_table(self):
        html_data = '<table><tbody><tr><td>Data1</td><td>Data2</td></tr><tr><td>Data3</td><td>Data4</td></tr></tbody></table>'
        soup = BeautifulSoup(html_data, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        expected_result = [['Data1', 'Data2'], ['Data3', 'Data4']]
        assert result == expected_result, "The function fails to iterate through a valid table."

    def test_table_row_data_iter_no_tbody(self):
        html_data = '<table><tr><td>Data1</td><td>Data2</td></tr><tr><td>Data3</td><td>Data4</td></tr></table>'
        soup = BeautifulSoup(html_data, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        assert result == [], "The function fails to return an empty iterator when a table lacks tbody."

    def test_table_row_data_iter_no_data(self):
        html_data = '<table><tbody></tbody></table>'
        soup = BeautifulSoup(html_data, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        assert result == [], "The function fails to return an iterator yielding empty list when there's no data in a table."

    def test_table_row_data_iter_nested_tables(self):
        html_data = '<table><tbody><tr><td>Data1</td><td><table><tbody><tr><td>NestedData</td></tr></tbody></table></td></tr></tbody></table>'
        soup = BeautifulSoup(html_data, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        assert result == [['Data1', '']], "The function is unable to handle nested tables correctly."
