# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=table_row_data_iter_93090a5698
ROOST_METHOD_SIG_HASH=table_row_data_iter_2cb334357f


```
Scenario 1: Test with a valid HTML table
Details:
  TestName: test_valid_html_table
  Description: This test is intended to verify that the function correctly iterates over a valid HTML table and extracts the text from each cell.
Execution:
  Arrange: Create a BeautifulSoup object with a valid HTML table.
  Act: Invoke the function with the BeautifulSoup object as a parameter.
  Assert: Check that the function returns an iterator that yields the correct data from each row of the table.
Validation:
  This test is important because it verifies the basic functionality of the function. The expected result is that the function correctly extracts the data from a valid HTML table, which is a key requirement of the function.

Scenario 2: Test with an empty HTML table
Details:
  TestName: test_empty_html_table
  Description: This test is intended to verify that the function correctly handles an empty HTML table.
Execution:
  Arrange: Create a BeautifulSoup object with an empty HTML table.
  Act: Invoke the function with the BeautifulSoup object as a parameter.
  Assert: Check that the function returns an iterator that does not yield any data.
Validation:
  This test is important because it verifies that the function can handle edge cases. The expected result is that the function correctly handles an empty table, which is a key requirement of the function.

Scenario 3: Test with a HTML table with nested tables
Details:
  TestName: test_nested_html_table
  Description: This test is intended to verify that the function correctly handles a HTML table with nested tables.
Execution:
  Arrange: Create a BeautifulSoup object with a HTML table that contains nested tables.
  Act: Invoke the function with the BeautifulSoup object as a parameter.
  Assert: Check that the function returns an iterator that yields the correct data from each row of the outer table, and ignores the nested tables.
Validation:
  This test is important because it verifies that the function can handle complex HTML structures. The expected result is that the function correctly extracts data from the outer table and ignores the nested tables, which is a key requirement of the function.

Scenario 4: Test with a non-table HTML element
Details:
  TestName: test_non_table_html_element
  Description: This test is intended to verify that the function correctly handles a non-table HTML element.
Execution:
  Arrange: Create a BeautifulSoup object with a non-table HTML element.
  Act: Invoke the function with the BeautifulSoup object as a parameter.
  Assert: Check that the function returns an iterator that does not yield any data.
Validation:
  This test is important because it verifies that the function can handle invalid input. The expected result is that the function correctly handles a non-table HTML element, which is a key requirement of the function.
```
"""

# ********RoostGPT********
import pytest
from bs4 import BeautifulSoup, Tag
from collections.abc import Iterator
from html_extract import table_row_data_iter

class Test_HtmlExtractTableRowDataIter:

    @pytest.mark.regression
    def test_valid_html_table(self):
        html = """
        <table>
            <tbody>
                <tr>
                    <td>Cell 1</td>
                    <td>Cell 2</td>
                </tr>
                <tr>
                    <td>Cell 3</td>
                    <td>Cell 4</td>
                </tr>
            </tbody>
        </table>
        """
        soup = BeautifulSoup(html, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        assert result == [['Cell 1', 'Cell 2'], ['Cell 3', 'Cell 4']]

    @pytest.mark.regression
    def test_empty_html_table(self):
        html = """
        <table>
            <tbody>
            </tbody>
        </table>
        """
        soup = BeautifulSoup(html, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        assert result == []

    @pytest.mark.regression
    def test_nested_html_table(self):
        html = """
        <table>
            <tbody>
                <tr>
                    <td>Cell 1</td>
                    <td>
                        <table>
                            <tbody>
                                <tr>
                                    <td>Nested Cell 1</td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>Cell 2</td>
                    <td>Cell 3</td>
                </tr>
            </tbody>
        </table>
        """
        soup = BeautifulSoup(html, 'html.parser')
        result = list(table_row_data_iter(soup.table))
        assert result == [['Cell 1', ''], ['Cell 2', 'Cell 3']]

    @pytest.mark.regression
    def test_non_table_html_element(self):
        html = """
        <div>
            <p>Paragraph 1</p>
            <p>Paragraph 2</p>
        </div>
        """
        soup = BeautifulSoup(html, 'html.parser')
        result = list(table_row_data_iter(soup.div))
        assert result == []
