# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type  and AI Model 

ROOST_METHOD_HASH=greeting_89aec8ad4f
ROOST_METHOD_SIG_HASH=greeting_11381d890c


```
Scenario 1: Test greeting without parameters
Details:
  TestName: test_greeting_without_parameters
  Description: Verify the default value of the parameter 'who' in the greeting function. This checks the function's functionality when no 'who' argument is provided.
Execution:
  Arrange: No setup is needed as no parameters are passed.
  Act: Invoke the function greeting without passing any parameters.
  Assert: Check if the output is "Hello, World!".
Validation:
  This test is crucial in validating the default behaviour of the function. If the function is invoked without passing the 'who' argument, the function must return "Hello, World!". This functionality is derived from the function's specifications.

Scenario 2: Test greeting with parameter
Details:
  TestName: test_greeting_with_parameter
  Description: This test aims to validate the function's behaviour when an argument is provided for 'who'. This will check the function's ability to properly integrate and manipulate given arguments.
Execution:
  Arrange: Decide on a string to pass as 'who'. 
  Act: Invoke the function greeting with the 'who' parameter you arranged.
  Assert: The output should be 'Hello, ' plus the value of the 'who' argument, ending with an exclamation mark.
Validation:
  This test is critical for ensuring that given parameters are used appropriately by the function. This has direct implications on the function's usability; for instance, if a user calls the function with a specific argument for 'who', they expect the greeting message to be personalized accordingly.

Scenario 3: Test greeting with special characters
Details:
  TestName: test_greeting_with_special_characters
  Description: This test is set to verify the function's ability to handle and output special characters.
Execution:
  Arrange: Prepare a string with special characters to pass as 'who'.
  Act: Invoke the function greeting with the special character string for 'who'.
  Assert: The output should be 'Hello, ' plus the special character string, ending with an exclamation mark.
Validation:
  This test case is important for the application's robustness. Since the function specification doesn't limit to alphanumeric characters for the 'who' argument, the system must handle and correctly output the passed special characters.

```

"""

# ********RoostGPT********
import pytest
from src.hello_world import greeting
import io
import sys

class Test_HelloWorldGreeting:
    
    def test_greeting_without_parameters(self, capsys):
        greeting()
        captured = capsys.readouterr()
        assert captured.out == "Hello, World!\n"

    def test_greeting_with_parameter(self, capsys):
        greeting("Python")
        captured = capsys.readouterr()
        assert captured.out == "Hello, Python!\n"

    def test_greeting_with_special_characters(self, capsys):
        greeting("$pecial Ch@racters")
        captured = capsys.readouterr()
        assert captured.out == "Hello, $pecial Ch@racters!\n"
