# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=greeting_89aec8ad4f
ROOST_METHOD_SIG_HASH=greeting_11381d890c


```
Scenario 1: Test default greeting
Details:
  TestName: test_default_greeting
  Description: This test is intended to verify if the function correctly prints a default greeting when no arguments are passed.
Execution:
  Arrange: No setup is required as no arguments are passed.
  Act: Invoke the function without passing any arguments.
  Assert: Check if the output is "Hello, World!".
Validation:
  This test is important as it checks the function's ability to handle cases when no arguments are passed, which is crucial for its default behavior.

Scenario 2: Test greeting with a specific name
Details:
  TestName: test_greeting_with_name
  Description: This test is intended to verify if the function correctly prints a personalized greeting when a name is passed as an argument.
Execution:
  Arrange: Prepare a string variable with a name.
  Act: Invoke the function passing the name as an argument.
  Assert: Check if the output is "Hello, {name}!" where {name} is the name passed as an argument.
Validation:
  This test is important as it checks the function's ability to correctly personalize the greeting based on the passed argument, which is a key requirement of the function.

Scenario 3: Test greeting with empty string
Details:
  TestName: test_greeting_with_empty_string
  Description: This test is intended to verify how the function handles cases when an empty string is passed as an argument.
Execution:
  Arrange: Prepare an empty string variable.
  Act: Invoke the function passing the empty string as an argument.
  Assert: Check if the output is "Hello, !".
Validation:
  This test is important as it checks the function's ability to handle cases when an empty string is passed, ensuring it doesn't crash or behave unexpectedly.

Scenario 4: Test greeting with special characters
Details:
  TestName: test_greeting_with_special_characters
  Description: This test is intended to verify how the function handles cases when a string with special characters is passed as an argument.
Execution:
  Arrange: Prepare a string variable with special characters.
  Act: Invoke the function passing the string with special characters as an argument.
  Assert: Check if the output is "Hello, {special_chars}!" where {special_chars} is the string with special characters passed as an argument.
Validation:
  This test is important as it checks the function's ability to handle cases when a string with special characters is passed, ensuring it doesn't crash or behave unexpectedly.
```
"""

# ********RoostGPT********
import pytest
from hw import greeting
import io
import sys

class Test_HwGreeting:
    @pytest.mark.regression
    def test_default_greeting(self, capsys):
        greeting()
        captured = capsys.readouterr()
        assert captured.out == "Hello, World!\n"

    @pytest.mark.regression
    def test_greeting_with_name(self, capsys):
        name = "Alice"
        greeting(name)
        captured = capsys.readouterr()
        assert captured.out == f"Hello, {name}!\n"

    @pytest.mark.regression
    def test_greeting_with_empty_string(self, capsys):
        empty_str = ""
        greeting(empty_str)
        captured = capsys.readouterr()
        assert captured.out == "Hello, !\n"

    @pytest.mark.regression
    def test_greeting_with_special_characters(self, capsys):
        special_chars = "@#^&"
        greeting(special_chars)
        captured = capsys.readouterr()
        assert captured.out == f"Hello, {special_chars}!\n"
