# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type  and AI Model 

ROOST_METHOD_HASH=greeting_89aec8ad4f
ROOST_METHOD_SIG_HASH=greeting_11381d890c


Scenario 1: Functionality when provided a valid string argument
Details:
  TestName: test_greeting_with_valid_string
  Description: This test verifies the behaviour of the greeting function when provided with a valid string argument.
Execution:
  Arrange: No setup is required for this simple function.
  Act: Call the greeting function with a string argument, for example, "John".
  Assert: The function should print "Hello, John!".
Validation:
  This test ensures that the greeting function correctly formats and prints the message when provided a valid argument, consistent with the specifications and requirements.

Scenario 2: Functionality when no argument is given
Details:
  TestName: test_greeting_with_no_argument
  Description: This test verifies the behaviour of the greeting function when called with no arguments.
Execution:
  Arrange: No setup is required for this simple function.
  Act: Simply call the greeting function without any argument.
  Assert: The function should print "Hello, World!".
Validation:
  This test checks the default parameter of the greeting function. It ensures that it is functioning correctly, providing the expected output of "Hello, World!" when no argument is given.

Scenario 3: Special character handling
Details:
  TestName: test_greeting_with_special_characters
  Description: This test verifies the handling of special characters by the greeting function.
Execution:
  Arrange: No setup is required for this simple function. 
  Act: Call the greeting function with a string containing special characters, for example, "!@#".
  Assert: The function should print "Hello, !@#!".
Validation:
  This test verifies that the greeting function correctly prints special characters along with the constant string "Hello, ". It helps ensure the function has a good level of robustness and correctly handles different types of string inputs.
"""

# ********RoostGPT********
import pytest
import sys
import io
from src.hello_world import greeting

class Test_HelloWorldGreeting:

    @pytest.mark.positive
    def test_greeting_with_valid_string(self, capsys):
        greeting("John")
        captured = capsys.readouterr()
        assert captured.out.strip() == "Hello, John!"

    @pytest.mark.positive
    def test_greeting_with_no_argument(self, capsys):
        greeting()
        captured = capsys.readouterr()
        assert captured.out.strip() == "Hello, World!"

    @pytest.mark.negative
    def test_greeting_with_special_characters(self, capsys):
        greeting("!@#")
        captured = capsys.readouterr()
        assert captured.out.strip() == "Hello, !@#!"
