[pytest]
markers =
    regression: mark a test as regression scenario
    smoke: mark a test as smoke scenario
    negative: mark a test as negative scenario
    valid: mark a test as valid scenario
    unit: mark a test as unit scenario
