[pytest]
markers =
    regression: mark a test as regression scenario
    valid: mark a test as valid scenario
    parametrize: mark a test as parametrize scenario
    run: mark a test as run scenario
    smoke: mark a test as smoke scenario
    negative: mark a test as negative scenario
    positive: mark a test as positive scenario
    performance: mark a test as performance scenario
    invalid: mark a test as invalid scenario
    security: mark a test as security scenario
    sample: mark a test as sample scenario
    regular: mark a test as regular scenario
    output: mark a test as output scenario
    error: mark a test as error scenario
    edge: mark a test as edge scenario
