# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___b2df5d4e5e
ROOST_METHOD_SIG_HASH=__init___e22f3e4fc5


```
Scenario 1: Valid Credentials
Details:
  TestName: test_valid_credentials_formation
  Description: This test is intended to verify the correct formation of the credentials object when provided valid inputs.
Execution:
  Arrange: Prepare a dictionary with 'username' and 'key'.
  Act: Invoke the __init__ function with the prepared dictionary as input parameter.
  Assert: Check if the credentials object is an instance of requests.auth.HTTPBasicAuth, and its username and password attributes are correctly assigned.
Validation:
  This test scenario ensures that with valid inputs, the function forms a valid requests.auth.HTTPBasicAuth object, confirming its positive functionality.        

Scenario 2: Missing or Invalid Credentials
Details:
  TestName: test_invalid_credentials_formation
  Description: This test verifies how the function behaves when the input dictionary doesn't contain one or both of the username and key.
Execution:
  Arrange: Prepare a dictionary missing one or both of 'username' and 'key'.
  Act: Invoke the __init__ function with the prepared dictionary.
  Assert: The function should throw a KeyError as it tries to access a non-existent key in the dictionary.
Validation:
  This scenario is important to ensure that the function should throw an error when provided with invalid inputs.

Scenario 3: Verification of Immutable Function
Details:
  TestName: test_init_immutable
  Description: This test is intended to ascertain that initializing the function multiple times does not affect the previously created instances.
Execution:
  Arrange: Initialize the function with a set of valid inputs.
  Act: Re-initialize the function with a different set of valid inputs.
  Assert: Check that the affixed details of the initial function instance have not changed following the re-initialization.
Validation:
  This maintains the idempotency property of the function, ensuring that each function call has an isolated effect, which is vital to the rigorousness and robustness of the encapsulated business logic.
```

"""

# ********RoostGPT********
import pytest
import requests
from kaggle_client import RestAccess

class Test_RestAccessInit:

    @pytest.mark.valid
    def test_valid_credentials_formation(self):
        valid_credentials = {'username': 'testUser', 'key': 'testKey'}
        kaggle_client = RestAccess(valid_credentials)

        assert isinstance(kaggle_client.credentials, requests.auth.HTTPBasicAuth)
        assert kaggle_client.credentials.username == 'testUser'
        assert kaggle_client.credentials.password == 'testKey'

    @pytest.mark.invalid
    def test_invalid_credentials_formation(self):
        invalid_credentials = {'username': 'testUser'}
        with pytest.raises(KeyError):
            RestAccess(invalid_credentials)
        
    @pytest.mark.immutable
    def test_init_immutable(self):
        initial_credentials = {'username': 'firstUser', 'key': 'firstKey'}
        update_credentials = {'username': 'secondUser', 'key': 'secondKey'}

        first_instance = RestAccess(initial_credentials)
        RestAccess(update_credentials)

        assert first_instance.credentials.username == 'firstUser'
        assert first_instance.credentials.password == 'firstKey'
