# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=find_table_caption_b23b2fe0bf
ROOST_METHOD_SIG_HASH=find_table_caption_09a7b31375


```
Scenario 1: Test with valid BeautifulSoup object and caption_text
Details:
  TestName: test_find_table_caption_valid_input
  Description: This test verifies that the function correctly identifies and returns the table with the specified caption_text from the BeautifulSoup object.
Execution:
  Arrange: Create a BeautifulSoup object with at least one table that has a caption matching the caption_text.
  Act: Call the find_table_caption function with the BeautifulSoup object and the caption_text.
  Assert: Check that the returned table is the correct one (i.e., it has the specified caption_text).
Validation:
  This test is important because it verifies the primary functionality of the function. If the function cannot correctly identify and return the table with the specified caption_text, it is not meeting its specifications.

Scenario 2: Test with valid BeautifulSoup object but no matching caption_text
Details:
  TestName: test_find_table_caption_no_matching_caption
  Description: This test verifies that the function correctly raises a RuntimeError when no table with the specified caption_text is found in the BeautifulSoup object.
Execution:
  Arrange: Create a BeautifulSoup object with at least one table, but none that have a caption matching the caption_text.
  Act: Call the find_table_caption function with the BeautifulSoup object and the caption_text.
  Assert: Check that a RuntimeError is raised with the correct error message.
Validation:
  This test is important because it verifies that the function correctly handles the scenario where no table with the specified caption_text is found. This is a necessary part of the function's error handling.

Scenario 3: Test with valid BeautifulSoup object but no tables
Details:
  TestName: test_find_table_caption_no_tables
  Description: This test verifies that the function correctly raises a RuntimeError when the BeautifulSoup object contains no tables.
Execution:
  Arrange: Create a BeautifulSoup object with no tables.
  Act: Call the find_table_caption function with the BeautifulSoup object and any caption_text.
  Assert: Check that a RuntimeError is raised with the correct error message.
Validation:
  This test is important because it verifies that the function correctly handles the scenario where the BeautifulSoup object contains no tables. This is a necessary part of the function's error handling.

Scenario 4: Test with invalid BeautifulSoup object
Details:
  TestName: test_find_table_caption_invalid_soup
  Description: This test verifies that the function correctly raises an error when an invalid BeautifulSoup object is passed.
Execution:
  Arrange: Create an invalid BeautifulSoup object (e.g., a string or a list).
  Act: Call the find_table_caption function with the invalid BeautifulSoup object and any caption_text.
  Assert: Check that an appropriate error is raised.
Validation:
  This test is important because it verifies that the function correctly handles the scenario where an invalid BeautifulSoup object is passed. This is a necessary part of the function's error handling.
```
"""

# ********RoostGPT********
import pytest
from bs4 import BeautifulSoup, Tag
from webpage_client import find_table_caption

class Test_WebpageClientFindTableCaption:

    @pytest.mark.valid
    def test_find_table_caption_valid_input(self):
        html_doc = """
        <html><head><title>Test Page</title></head>
        <body>
        <table>
        <caption>Anscombe's quartet</caption>
        <tr><td>1</td><td>2</td></tr>
        </table>
        </body></html>
        """
        soup = BeautifulSoup(html_doc, 'html.parser')
        result = find_table_caption(soup, "Anscombe's quartet")
        assert isinstance(result, Tag)
        assert result.caption.text.strip() == "Anscombe's quartet"

    @pytest.mark.negative
    def test_find_table_caption_no_matching_caption(self):
        html_doc = """
        <html><head><title>Test Page</title></head>
        <body>
        <table>
        <caption>Test Caption</caption>
        <tr><td>1</td><td>2</td></tr>
        </table>
        </body></html>
        """
        soup = BeautifulSoup(html_doc, 'html.parser')
        with pytest.raises(RuntimeError, match=r"<table> with caption 'Anscombe's quartet' not found"):
            find_table_caption(soup, "Anscombe's quartet")

    @pytest.mark.negative
    def test_find_table_caption_no_tables(self):
        html_doc = """
        <html><head><title>Test Page</title></head>
        <body>
        <p>No tables here!</p>
        </body></html>
        """
        soup = BeautifulSoup(html_doc, 'html.parser')
        with pytest.raises(RuntimeError, match=r"<table> with caption 'Anscombe's quartet' not found"):
            find_table_caption(soup, "Anscombe's quartet")

    @pytest.mark.invalid
    def test_find_table_caption_invalid_soup(self):
        invalid_soup = "This is not a BeautifulSoup object"
        with pytest.raises(TypeError):
            find_table_caption(invalid_soup, "Anscombe's quartet")
