# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonrealworldtest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=__init___b2df5d4e5e
ROOST_METHOD_SIG_HASH=__init___e22f3e4fc5


Scenario 1: Valid credentials provided
Details:
  TestName: test_valid_credentials
  Description: This test is intended to verify that the function correctly creates an HTTPBasicAuth object when provided with a valid username and key.
Execution:
  Arrange: Initialize a dictionary with a valid 'username' and 'key'.
  Act: Invoke the function with the prepared dictionary.
  Assert: Check that the function creates an HTTPBasicAuth object with the correct username and key.
Validation:
  This test is important because it verifies that the function correctly handles valid input. The expected result is that the function creates an HTTPBasicAuth object with the correct username and key, which is in line with the function's specifications and business requirements.

Scenario 2: Invalid credentials provided
Details:
  TestName: test_invalid_credentials
  Description: This test is intended to verify that the function raises an appropriate error when provided with an invalid username or key.
Execution:
  Arrange: Initialize a dictionary with an invalid 'username' or 'key'.
  Act: Invoke the function with the prepared dictionary.
  Assert: Check that the function raises an appropriate error.
Validation:
  This test is important because it verifies that the function correctly handles invalid input. The expected result is that the function raises an appropriate error, which is in line with the function's specifications and business requirements.

Scenario 3: Missing credentials
Details:
  TestName: test_missing_credentials
  Description: This test is intended to verify that the function raises an appropriate error when the provided dictionary does not contain a 'username' or 'key'.
Execution:
  Arrange: Initialize a dictionary without a 'username' or 'key'.
  Act: Invoke the function with the prepared dictionary.
  Assert: Check that the function raises an appropriate error.
Validation:
  This test is important because it verifies that the function correctly handles missing input. The expected result is that the function raises an appropriate error, which is in line with the function's specifications and business requirements.
"""

# ********RoostGPT********
import pytest
import requests
from kaggle_client import RestAccess

class Test_RestAccessInit:

    @pytest.mark.valid
    def test_valid_credentials(self):
        # Arrange
        valid_credentials = {'username': 'valid_username', 'key': 'valid_key'}
        rest_access = RestAccess(valid_credentials)

        # Act
        credentials = rest_access.credentials

        # Assert
        assert isinstance(credentials, requests.auth.HTTPBasicAuth)
        assert credentials.username == 'valid_username'
        assert credentials.password == 'valid_key'

    @pytest.mark.invalid
    def test_invalid_credentials(self):
        # Arrange
        invalid_credentials = {'username': 'invalid_username', 'key': 'invalid_key'}

        # Act and Assert
        with pytest.raises(Exception):
            RestAccess(invalid_credentials)

    @pytest.mark.negative
    def test_missing_credentials(self):
        # Arrange
        missing_credentials = {'username': 'missing_username'}

        # Act and Assert
        with pytest.raises(KeyError):
            RestAccess(missing_credentials)
