# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=series_iter_14a6249a86
ROOST_METHOD_SIG_HASH=series_iter_f84b65f841


```
Scenario 1: Confirm the series_iter function correctly executes the names query.
Details:
  TestName: test_series_iter_names_query_execution
  Description: This test will ensure that the function is correctly executing the query to retrieve the names.
Execution:
  Arrange: Mock a connection object and set up a config dictionary that includes a 'query' key with a 'names' subkey, mapping to the string of the SQL query the function should execute.
  Act: Call the series_iter function with the mocked connection and the prepared config.
  Assert: Confirm that the correct query string has been received by the mocked database execution method.
Validation:
  This test validates if series_iter function is able to correctly execute the SQL query provided in the config dictionary to retrieve the names, ensuring its functionality and business logic.

Scenario 2: Validate series_iter successfully yields the correct Series objects in order.
Details:
  TestName: test_series_iter_yields_correct_series
  Description: This test will check that the series_iter function yields the correct objects of names and sample pairs.
Execution:
  Arrange: Mock a connection object and provide a config dictionary with two sets of query names, each associated with a sample data set. Mock the build_samples method to return the related samples for each name.
  Act: Call the series_iter function with the mocked objects and config.
  Assert: Confirm that the yield from the series_iter function matches the expected Series objects in the correct order.
Validation:
  This test confirms that series_iter is correctly pairing the names and samples from the database and generating the right model.Series objects.

Scenario 3: Check that build_samples function is correctly called by series_iter
Details:
  TestName: test_series_iter_calls_build_samples_correctly
  Description: This test verifies that the series_iter function calls the build_samples function with the appropriate parameters.
Execution:
  Arrange: Mock a connection object, the build_samples method, and prepare a config containing a 'query' key with 'names' and 'samples' subkeys both mapping to SQL query strings.
  Act: Invoke the series_iter method with the mocked objects and config.
  Assert: Confirm the build_samples function was called with the correct parameters.
Validation:
  This test ensures that the series_iter function calls build_samples correctly with the right parameters for each row from the names_cursor. This maintains data consistency and the integrity of the function’s business logic.

Scenario 4: Test the functioning of the series_iter with an empty database
Details:
  TestName: test_series_iter_with_empty_database
  Description: This test checks how the series_iter behaves when the database has no data.
Execution:
  Arrange: Mock a connection object and provide a config dictionary with the 'query' key and 'names' subkey, and let the names query return no data.
  Act: Call the series_iter function with the mocked objects and config.
  Assert: Check that the function correctly handles this situation and does not yield any items.
Validation:
  This test is important to ensure the function can handle edge cases and confirm it does not raise errors or cause issues when the database is empty.
```
"""

# ********RoostGPT********
import pytest
import sqlite3
from collections.abc import Iterator
import model
from unittest.mock import Mock, MagicMock
from db_extract import Extract


class Test_ExtractSeriesIter:
    
    @pytest.mark.regression
    def test_series_iter_names_query_execution(self):
        mock_conn = MagicMock(sqlite3.Connection)
        config = {'query': {'names': 'SELECT * FROM names'}}
        extract = Extract()
        
        list(extract.series_iter(mock_conn, config))
        
        mock_conn.execute.assert_called_once_with('SELECT * FROM names')

    @pytest.mark.regression
    def test_series_iter_yields_correct_series(self):
        mock_conn = MagicMock(sqlite3.Connection)
        extract = Extract()

        # Mock the return value of fetchall() method
        mock_conn.execute().fetchall.side_effect = [('name1', ), ('name2', )]

        config = {'query': {'names': 'SQL QUERY 1', 'samples': 'SQL QUERY 2'}}
        
        # Mock the build_samples() function to return "expected" samples
        mock_build_samples = MagicMock(return_value='expected_samples')
        extract.build_samples = mock_build_samples

        result = list(extract.series_iter(mock_conn, config))

        # Check if the correct objects were returned
        assert result == [model.Series('name1', 'expected_samples'), model.Series('name2', 'expected_samples')]
    
    @pytest.mark.regression
    def test_series_iter_calls_build_samples_correctly(self):
        mock_conn = MagicMock(sqlite3.Connection)
        extract = Extract()
        mock_conn.execute().fetchall.side_effect = [('name1', ), ('name2', )]

        config = {'query': {'names': 'SQL QUERY 1', 'samples': 'SQL QUERY 2'}}

        # Mock the build_samples() function to not do anything
        mock_build_samples = Mock()
        extract.build_samples = mock_build_samples

        list(extract.series_iter(mock_conn, config))
        
        # Check if the build_samples() was called with correct parameters
        mock_build_samples.assert_any_call(mock_conn, config, 'name1')
        mock_build_samples.assert_any_call(mock_conn, config, 'name2')

    @pytest.mark.negative
    def test_series_iter_with_empty_database(self):
        mock_conn = MagicMock(sqlite3.Connection)
        extract = Extract()
        mock_conn.execute().fetchall.return_value = []

        config = {'query': {'names': 'SQL QUERY 1', 'samples': 'SQL QUERY 2'}}

        result = list(extract.series_iter(mock_conn, config))

        # Check that no items were yielded
        assert result == []
