# ********RoostGPT********
"""
Test generated by RoostGPT for test pythbctesting2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythbctesting2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=series_iter_14a6249a86
ROOST_METHOD_SIG_HASH=series_iter_f84b65f841


```
Scenario 1: Validate correct Series generation with sample data
Details:
  TestName: test_correct_series_generation
  Description: This test verifies that a correct Series is returned, given a valid connection and configurations. The function should iterate over the names, fetch samples and present the data in the model.Series format. It also ensures the program's correctness when multiple rows are returned from names_cursor.
Execution:
  Arrange: Create a mock SQLite connection and a configuration dictionary containing the required 'query' with 'names' key. Also prepare mock data for names_cursor and samples corresponding to each name.
  Act: Invoke the series_iter method with the mock connection and the config dictionary.
  Assert: Validate that the series returned per iteration match with the prepared samples and has all the correct names.
Validation:
  This test ensures data integrity and that the function appropriately translates raw database row data into Python data structures. It's a critical validation of the method's primary functionality.

Scenario 2: Test handling of empty rows from names_cursor
Details:
  TestName: test_empty_rows
  Description: This test ensures correct behavior of 'series_iter' when no rows are fetched using the 'names' query, i.e., the 'names_cursor' is empty.
Execution:
  Arrange: Prepare a mock SQLite connection and a configuration dictionary containing the required 'query' with 'names' key. Ensure that fetching using 'names' query results in no rows.
  Act: Invoke 'series_iter' method with the mock connection and the config dictionary.
  Assert: The iterator should not yield anything and complete without throwing errors.
Validation:
  The test shows the ability of the function to handle cases where no data rows are returned by the 'names' query correctly. It's essential to ensure function reliability and robustness.

Scenario 3: Validate proper error handling during database operation
Details:
  TestName: test_database_operation_errors
  Description: This test is intended to validate the method's behavior when there's an exception during the execution of the database query.
Execution:
  Arrange: Create the necessary mock SQLite connection and config dictionary. Make the method call to execute throw an exception.
  Act: Call the series_iter method with the prepared mock connection and the config dictionary.
  Assert: Verify that the method properly handles the exception from the database operation and, as a result, it terminates gracefully.
Validation:
  It assures the smooth operation of the function during failure scenarios during database operations, and also ensures robustness of the application.
```
"""

# ********RoostGPT********
import pytest
import sqlite3
from typing import Any
from unittest.mock import Mock
from collections.abc import Iterator
import model
from db_extract import Extract

class Test_ExtractSeriesIter:

    @pytest.mark.regression
    def test_correct_series_generation(self):
        mock_connection = Mock(spec=sqlite3.Connection)
        mock_config = {'query': {'names': 'SELECT NAME FROM TEST'}}
        sample_data = [('name1',), ('name2',)]
        mock_samples = [model.Samples(name='name1', values=[1,2]), model.Samples(name='name2', values=[3,4])]

        mock_connection.execute.return_value = iter(sample_data)
        extractor = Extract()
        # mock the build_samples function
        extractor.build_samples = Mock()
        extractor.build_samples.side_effect = mock_samples  

        result_series = list(extractor.series_iter(mock_connection, mock_config))

        # Assert
        assert len(result_series)==len(sample_data)  # all names are converted to series
        for series, name, sample in zip(result_series, sample_data, mock_samples):
            assert series.name == name[0]
            assert series.samples == sample


    @pytest.mark.negative
    def test_empty_rows(self):
        mock_connection = Mock(spec=sqlite3.Connection)
        mock_config = {'query': {'names': 'SELECT NAME FROM TEST'}}
        extractor = Extract()

        mock_connection.execute.return_value = iter([])
        result_series = list(extractor.series_iter(mock_connection, mock_config))

        # Assert
        assert len(result_series) == 0  # no series should be returned


    @pytest.mark.negative
    def test_database_operation_errors(self):
        mock_connection = Mock(spec=sqlite3.Connection)
        mock_config = {'query': {'names': 'SELECT NAME FROM TEST'}}

        mock_connection.execute.side_effect = sqlite3.OperationalError('some error')
        extractor = Extract()

        with pytest.raises(sqlite3.OperationalError) as excinfo:
            list(extractor.series_iter(mock_connection, mock_config))

        # Assert
        assert 'some error' in str(excinfo.value)
