# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonrealworldtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___c96b4e4023
ROOST_METHOD_SIG_HASH=__init___42efece3c8


Scenario 1: Correctly Initialize the builders parameter
Details:
  TestName: test_init_correctly_sets_builders
  Description: Testing if the "__init__" method correctly initializes its builders attribute with the provided parameter.
Execution:
  Arrange: Prepare a list of mock PairBuilder instances.
  Act: Initialize the object using the prepared list of PairBuilders.
  Assert: Check if the builders attribute matches the list that was passed in.
Validation:
  It's important to ensure the "__init__" method works correctly, as it sets up the state of the object. Any misbehavior might impact other functions, which rely on the correctly-initialized state of the object.

Scenario 2: Builders parameter is mutable after initialization
Details:
  TestName: test_builders_parameter_is_mutable
  Description: Testing if the builders attribute is mutable after object initialization.
Execution:
  Arrange: Prepare a list of mock PairBuilder instances and initialize the object.
  Act: Append a new PairBuilder instance to the builders attribute.
  Assert: Check if the builders attribute was updated correctly.
Validation:
  The builders attribute may need to be adjusted during the lifetime of the object. Hence, testing its mutability is essential to ensure the class is working as expected.

Scenario 3: Builders parameter is not None
Details:
  TestName: test_builders_parameter_not_none
  Description: Testing if the "__init__" method raises an appropriate error when None is passed to the builders parameter.
Execution:
  Arrange: No arrangement needed.
  Act: Attempt to initialize the object with a None builders parameter.
  Assert: Check if the appropriate exception is raised.
Validation:
  The builders parameter is a required parameter in the initialization of the object and thus should not be None. It's essential to ensure the correctness of our object creation.

Scenario 4: Builders list can be empty
Details:
  TestName: test_empty_builders_list
  Description: Testing if the "__init__" method correctly initializes its builders attribute with an empty list.
Execution:
  Arrange: Prepare an empty list.
  Act: Initialize the object with the empty list.
  Assert: Check if the builders attribute is an empty list.
Validation: 
  An object might be initialized with no builders, and added later. We need to ensure that our class can handle this scenario properly.
"""

# ********RoostGPT********
import pytest
from unittest.mock import Mock, sentinel, call
from model import RawData, XYPair
from abc import ABC, abstractmethod
import csv
from pathlib import Path
from csv_extract import Extract


class Test_ExtractInit:

    @pytest.mark.regression
    def test_init_correctly_sets_builders(self):
        mock_builder_list = [Mock(), Mock(), Mock()]
        extract_obj = Extract(mock_builder_list)

        assert extract_obj.builders == mock_builder_list

    @pytest.mark.regression
    def test_builders_parameter_is_mutable(self):
        mock_builder_list = [Mock(), Mock(), Mock()]
        extract_obj = Extract(mock_builder_list)

        new_builder = Mock()
        extract_obj.builders.append(new_builder)
        
        assert extract_obj.builders == mock_builder_list + [new_builder]

    @pytest.mark.negative
    def test_builders_parameter_not_none(self):
        with pytest.raises(TypeError):
            extract_obj = Extract(None)

    @pytest.mark.valid
    def test_empty_builders_list(self):
        empty_list = []
        extract_obj = Extract(empty_list)

        assert extract_obj.builders == empty_list
